@TmsApi_HostAddress = http://localhost:5240

GET {{TmsApi_HostAddress}}/api/assessments/results
Accept: application/json
X-Training-User: student1
###

GET {{TmsApi_HostAddress}}/api/test/deferred
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/test/translation-fail
Accept: application/json