@TmsApi_HostAddress = http://localhost:5240

GET {{TmsApi_HostAddress}}/api/assessments/results
Accept: application/json
X-Training-User: student1
###

GET {{TmsApi_HostAddress}}/api/test/deferred
Accept: application/json
###
GET  {{TmsApi_HostAddress}}/api/enrollments
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/test/translation-fail
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/test/students-in-course/1
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/test/students-paged
Accept: application/json

###
GET {{TmsApi_HostAddress}}/api/test/average-gpa-per-course
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/v1/courses
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/v2/courses
Accept: application/json

###
GET {{TmsApi_HostAddress}}/api/courses
X-Api-Version: 1.0
Accept: application/json

###
GET {{TmsApi_HostAddress}}/api/courses
X-Api-Version: 2.0
Accept: application/json
